SELECT *
FROM customer
LIMIT 10;

--what is the total revenue generated by male vs female customer?
SELECT  gender,
		SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


--Which customers used a discount but still spent more than the average purchase amount
SELECT customer_id,
		purchase_amount
FROM customer
WHERE purchase_amount > (SELECT AVG(purchase_amount) FROM customer) AND discount_applied = 'Yes'


--Which are the top 5 products with the highest avergae review rating
SELECT item_purchased,
		ROUND(AVG(review_rating)::numeric,2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


--compare the average purchase amounts between standard and express shipping
SELECT shipping_type,
		ROUND(AVG(purchase_amount), 2)
FROM customer
WHERE shipping_type in ('Express', 'Standard')
GROUP BY shipping_type

--do subscribed customers spend more?
--compare average spend and total revenue between suscribed and non-subscribed

SELECT subscription_status,
		COUNT(customer_id) AS "Number of customers",
		ROUND(AVG(purchase_amount), 2) AS avg_spend,
		ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;


--Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
		ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)::numeric /COUNT(*) *100,2) AS discount_rate
FROM customer
group BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Segment customers into new, returning and loyal based on theirnumber of previous purchases
WITH customer_type AS (
	SELECT customer_id, previous_purchases,
		CASE WHEN previous_purchases = 1 THEN 'New'
			 When previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			 ELSE 'Loyal'
			 END AS customer_segment
	FROM customer
)
SELECT customer_segment,
	   COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--What are the top 3 most purchased products within each category?

WITH item_counts AS (
	SELECT category,
		   item_purchased,
		   COUNT(customer_id) AS total_order,
		   ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
	FROM customer
	GROUP BY category, item_purchased
)
SELECT item_rank,
	   category,
	   item_purchased,
	   total_order
FROM item_counts
WHERE item_rank <= 3;

--ARe customers who are repeat buyers (more than 5 previous purchases) likely to subscribe?
WITH customer_type AS (
	SELECT customer_id, previous_purchases, subscription_status,
		CASE WHEN previous_purchases BETWEEN 1 AND 4 THEN 'New'
			 When previous_purchases => 5 'Repeat Buyers'
			 END AS customer_segment
	FROM customer
)


SELECT subscription_status,
	   COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases >5
GROUP BY subscription_status;



--What is the revenue contribution of each age group?

SELECT age_group,
	   COUNT(*) AS number_customers,
	   ROUND(AVG(purchase_amount), 2) AS average_spend,
	   ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;